FROM node:18-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN if [ -f package-lock.json ]; then npm ci; else npm install; fi
COPY . .
ARG REACT_APP_AUTH_API
ARG REACT_APP_PRODUCT_API
ARG REACT_APP_RAFFLE_API
ARG REACT_APP_INTERACTION_API
ARG REACT_APP_PAYMENT_API

ENV REACT_APP_AUTH_API=${REACT_APP_AUTH_API}
ENV REACT_APP_PRODUCT_API=${REACT_APP_PRODUCT_API}
ENV REACT_APP_RAFFLE_API=${REACT_APP_RAFFLE_API}
ENV REACT_APP_INTERACTION_API=${REACT_APP_INTERACTION_API}
ENV REACT_APP_PAYMENT_API=${REACT_APP_PAYMENT_API}

RUN npm run build

FROM node:18-alpine
RUN npm install -g serve@14
COPY --from=builder /app/build /app/build
EXPOSE 80
CMD ["serve", "-s", "/app/build", "-l", "80"]
